"""empty message

Revision ID: 022ddb162d08
Revises: cc27b04f0aae
Create Date: 2022-10-07 18:32:14.869607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022ddb162d08'
down_revision = 'cc27b04f0aae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
