"""empty message

Revision ID: a00794fa6a3d
Revises: 1bd524a55159
Create Date: 2022-10-11 07:38:15.628965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00794fa6a3d'
down_revision = '1bd524a55159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
